# Generated by Django 2.2.16 on 2021-12-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20211217_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'user'), ('moderator', 'moderator'), ('admin', 'admin')], default='admin', max_length=150, verbose_name='Роль'),
        ),
    ]
